### ISSUE TITLE
 Merge Hyperion into this repo

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/mx-bluesky#169]
We decided today that having the two `mx-bluesky` and `hyperion` repos is causing us too much dependency overhead. Hyperion should be merged into here.

Things that must happen when they are merged:
* Git history of hyperion is preserved
* All hyperion tests are still run and pass
* Issues on hyperion repo are moved to mx-bluesky (with an appropriate label)

Things that should happen (e.g. make a new issue for them if hard):
* The structure of `mx-bluesky` needs to be well documented
* All the GH actions that move things on the Hyperion project board still work (with the caveat that they only work on things tagged with the hyperion label)
* Slack messages on releases still get pushed to the `hyperion` channel

Things we would then like to add:
* Release notes are now going to be a bit messy, it would be nice to have an automated way of adding a `hyperion` heading to them

Nice to haves:
* Navigating to https://github.com/DiamondLightSource/hyperion redirects to https://github.com/DiamondLightSource/mx-bluesky

**Comment by DominicOram** [comment]
Proposed folder structure:
```
mx_bluesky
 - common
 - beamlines
    - i04
       - thawing.py
    - i24
       - ssx
 - hyperion
```

**Comment by dperl-dls** [comment]
Still TODO from the PR (copying here for easier linked issue generation):

- [ ] update the release workflow to work with pyproject.toml
- [ ] fix codecov integration
- [ ] get issue/project integration to work
- [ ] rework hyperion's readme & the wiki docs to the mx-bluesky sphinx docs structure
- [ ] move hyperion issues here and tag them
- [ ] update slack integration
- [ ] add a linting step to ensure clean import directionality
