### ISSUE TITLE
Decide on optimal panda grid scan parameters

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/mx-bluesky#217]
Discussions regarding PVT scans have lead to the following:

1) If we use time-based triggers, there will be an error in position, the size of which is somewhat determined by the run-up-distance.
2) If we use position-based triggers, there will be an error in time. To account for this, we would need to use the Eiger's variable exposure time and analysis would need to correctly weigh the positions based on their exposure time

We are trying 1. for now. 

Lower run-up distance means faster grid scan but more inaccurate trigger positions. We need to work out the lowest acceptable run-up distance. 

## Acceptance Criteria
- Use panda grid scans for a few days with PCAP enabled, varying the run-up distance and measuring total time taken
- Analyse the PCAP h5 files to see exactly how run-up affects trigger position accuracy and total time, and ultimately decide on the best number to use.

Requires DiamondLightSource/hyperion#1474 and DiamondLightSource/hyperion#1485

**Comment by olliesilvester** [comment]
After collecting some data and discussing with @DominicOram , @npat113, and @graeme-winter, we will use the PandA at the start of next run with a run-up distance of 0.2mm.

To get PandA working in time, we need to do https://github.com/DiamondLightSource/mx-bluesky/issues/502 before next run. I'll get on this

**Comment by DominicOram** [comment]
Could you add the graphs here that led us to that conclusion? Just for future reference. Also I guess some blurb on what exactly the graphs are showing/what we're doing to get the data

**Comment by olliesilvester** [comment]
![image](https://github.com/user-attachments/assets/1d23e8cc-2bf3-4183-9389-b9ad8cd3585b)
![image](https://github.com/user-attachments/assets/6f3cf06d-ced6-4919-93dd-0e391af51de2)
![image](https://github.com/user-attachments/assets/a9f09d27-edf7-44ba-96c4-deb2dc592a3a)

- This data was collected using 2 x 30 x 30 grid scans, with a smargon at 10mm/s, exposure time of 2ms, box size of 20 microns
- 'Triggers per second' = total triggers / motion wall time
- 'Bad points' = Points which were inaccurate by at least half a box size (error => 10 microns)
