### ISSUE TITLE
Document grid scan coordinate systems

### ISSUE THREAD

**Issue by rtuck99** [DiamondLightSource/mx-bluesky#221]
Rotations after xray centring sometimes are not aligned with the centre of the crystal, see:

Xray centred crystal: https://ispyb.diamond.ac.uk/dc/visit/cm37235-3/id/14661060
Manually centred same crystal: https://ispyb.diamond.ac.uk/dc/visit/cm37235-3/id/14661069

Observations after discussion with Mark, possibly this is multi-factorial:

* In `zocalo_results.py` we subtract a 0.5 box-width amount from the coordinates we get back from zocalo - it's not clear to me if this is correct or not, not knowing enough about how the analysis interprets its input data or what it outputs
* the number of data points for small crystals is very small (for some it may be a crystal only 2 x 1 x 1 boxes) and this may be affecting the quality of the returned centre-of-mass coordinate depending on the assumptions made in the analysis
* The heatmap superimposed on the grid in ispyb is somewhat misleading as it suggests we have more data than we really do - a discretised flat shading per box would be more representative than smooth shading interpolated from the limited data points

* Suggest that we reduce the grid size to collect more points per crystal, as per DiamondLightSource/mx-bluesky#231 
* Investigate if the 0.5 grid size correction is actually the correct thing to do.

**Comment by DominicOram** [comment]
We need to go through the whole stack and work out the coordinate systems and write a nice document on it

**Comment by rtuck99** [comment]
In testing on 1.4.1 #697 we are now seeing that ~about 10% of the time we are getting gridscans failing with 
```
File "/dls_sw/i03/software/bluesky/mx-bluesky_v1.4.1/dodal/src/dodal/devices/fast_grid_scan.py", line 107, in grid_position_to_motor_position
    raise IndexError(f"{grid_position} is outside the bounds of the grid")
```
where the x-axis of the crystal centre is -0.5 due to the applied correction and this falls outside a santity check for the grid box

**Comment by rtuck99** [comment]
PRs raised for dodal and mx-bluesky. There is also a PR TBC for `dlstbx`, which also should have https://github.com/DiamondLightSource/python-dlstbx/pull/253 reverted
