### ISSUE TITLE
FGS: Correctly configure zebra to allow manual shutter operation

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/mx-bluesky#232]
Whilst running the FGS we need to be sure that if there is an issue we can switch to manual operation of the shutter. The logic to do this controlled by a logic gate in the zebra. However, we have wired it up incorrectly and have bypassed this check.

## Acceptance Criteria
* During the fast grid scan a user is still able to set the shutter to manual operation through the EDM screen

**Comment by olliesilvester** [comment]
@DominicOram Just to clarify, is the intended behaviour here:

- During gridscan, set shutter to automatic, meaning it's controlled by the AND2 gate. The AND2 gate should be high when the motion controller sends a trigger (into TTL4)
- In gridscan cleanup, set shutter to manual, meaning it's controlled by the AND1 gate. This gate is controlled by two soft inputs, allowing you to turn close the shutter via EDM

- During rotations, set shutter to automatic, and control it via PC_GATE
- In rotation cleanup, set shutter back to manual

**Comment by DominicOram** [comment]
>@DominicOram Just to clarify, is the intended behaviour:

Yes, this is correct
