### ISSUE TITLE
Deploy script no longer gives console output when running dls_dev_env.sh

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/mx-bluesky#242]
After  thechanges in https://github.com/DiamondLightSource/hyperion/pull/1369, we no longer receive live terminal output when running `dls_dev_env.sh`, since the code now ssh's into i03-control to do this part. This makes it difficult to see if there are any errors when running that part of the script

## Acceptance Criteria

- Implement a way to see the SSH'd console output live, OR do https://github.com/DiamondLightSource/mx-bluesky/issues/250 instead

**Comment by DominicOram** [comment]
Fixed by containerizing
