### ISSUE TITLE
Linting always fails on merge into main 

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/mx-bluesky#455]
It looks like after a PR has been merged to `main` the linting will always fail as it runs the pre-commit hooks and picks it up as a direct commit into `main` rather than a PR that has been merged. e.g. https://github.com/DiamondLightSource/mx-bluesky/actions/runs/10717610932/job/29717663740

## Acceptance Criteria
- Merges into main do not fail CI
- `pre-commit` hooks run locally still prevent merging into main

**Comment by olliesilvester** [comment]
From what I can tell, we didn't have this issue in the Hyperion repo because we never ran any pre-commit in CI. Is removing pre-commit from our `ci.yml` an acceptable solution here?

**Comment by DominicOram** [comment]
If all the other checks that the pr-commit hooks do are done by CI still anyway thn that's ok. However, it would be nicer to have CI run the hooks with an exclude on the merge to main as if we want to add another check in the future we would have to add it to CI and the hooks rather than just the hooks if we know CI is running them anyway. It would also be good to see how the copier template handles this? I have a mild preference for just doing whatever that does

**Comment by olliesilvester** [comment]
https://github.com/bluesky/ophyd-async/blob/main/.pre-commit-config.yaml

Looks like the copier template doesn't have a `no-commit-to-main` hook. So we can either remove it from ours, or try and exclude it during CI. I think removing it is fine, since we can't push things to main anyway

**Comment by DominicOram** [comment]
> I think removing it is fine, since we can't push things to main anyway

Agreed
