### ISSUE TITLE
GDA timing out when hyperion is waiting for beam

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/mx-bluesky#485]
Last night the beam went down during https://ispyb.diamond.ac.uk/dc/visit/in37633-7/dcg/12777225. Hyperion correctly waited for the beam to come back up by GDA timed out on the hyperion call. For other hyperion calls we make sure not to time out if hyperion is waiting on beam to come back but the robot load + centring call does not do this.

## Acceptance Criteria
- GDA does not time out on the hyperion call if hyperion is waiting for beam to come back during a robot load + XRC

**Comment by DominicOram** [comment]
Fixed in https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/42610?usp=dashboard

**Comment by olliesilvester** [comment]
I'm happy that the above change addresses this issue, and it's already been merged so I'm closing this
