### ISSUE TITLE
 Scan i03's diamond filter

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/mx-bluesky#544]
i03 would like to scan their diamond filter. To do this they will need the device listed in https://jira.diamond.ac.uk/browse/I04-953 and to be able to read the QBPM. They would then need someone to guide them through how to scan over it in bluesky

## Acceptance Criteria
- The devices are in dodal (and work for both i03 and i04)
- The filter has been scanned over on the beamline to the scientists satisfaction

**Comment by DominicOram** [comment]
@DominicOram to book in a time on i03 to do this

**Comment by olliesilvester** [comment]
Did this on i03 at 3pm today, Neil has data in html file
