### ISSUE TITLE
 Fix unstable test for grid_detect_then_xray_centre_plan

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/mx-bluesky#653]
Our unit test `test_detect_grid_and_do_gridscan` occasionally fails. This is likely due to something not being cleaned up properly. See https://github.com/DiamondLightSource/mx-bluesky/actions/runs/11859361401/job/33052132442 for an instance of it failing

## Acceptance Criteria
- Improved test

**Comment by DominicOram** [comment]
I thought I had fixed this in https://github.com/DiamondLightSource/mx-bluesky/pull/661 but clearly haven't. However, I think the reasoning I have put there about why it's happening is sound
